### ISSUE TITLE
main menu UI 

### ISSUE THREAD

**Issue by Unlxii** [Unlxii/projectcompro#12]
UI 
หน้าจอเริ่มเกม
![exit](https://user-images.githubusercontent.com/87744652/218147788-0080cf3f-0808-4f7c-95d0-054765e1ee68.png)
![play](https://user-images.githubusercontent.com/87744652/218147795-86cd73a2-7629-4ae9-9012-d247740d4cbc.png)
![S](https://user-images.githubusercontent.com/87744652/218147799-37de9b2e-51bb-48be-807c-f86cb38012f9.png)
![setting](https://user-images.githubusercontent.com/87744652/218147803-4397a355-828c-47b2-825f-bd8e4875e065.png)
![title 2](https://user-images.githubusercontent.com/87744652/218147805-1197f8e6-5159-4135-8186-2847f0c04783.png)
![title](https://user-images.githubusercontent.com/87744652/218147810-f8c91b2d-ad6f-4dc5-ad56-2e5d0d52c3bf.png)

**Comment by Apinanchai** [comment]
![Main Menu](https://user-images.githubusercontent.com/110967577/219920316-707e849f-1a6a-4b01-9310-d18652f501e8.png)
![Settings Menu](https://user-images.githubusercontent.com/110967577/219920341-9247266f-365e-4bf3-be94-18524f6ddddc.png)
![GameTest](https://user-images.githubusercontent.com/110967577/219920363-7ebf5e44-71f9-4a6c-9c59-16be2ec66539.png)

**Comment by Unlxii** [comment]
https://drive.google.com/drive/folders/1WXlYS0l2HmyrxRARmbrJJ6IgU3igLivE
