### ISSUE TITLE
game concept 

### ISSUE THREAD

**Issue by Unlxii** [Unlxii/projectcompro#20]
[Your_Way.pdf](https://github.com/Unlxii/projectcompro/files/10757027/Your_Way.pdf)

**Comment by InHiBiToRs** [comment]
Minigame concept
[Mini_game.pdf](https://github.com/Unlxii/projectcompro/files/10806865/Mini_game.pdf)

**Comment by InHiBiToRs** [comment]
![Mini_game-1](https://user-images.githubusercontent.com/110962321/220714316-8d181e83-0a72-4c9f-8eb8-5db9e25372e9.jpg)
![Mini_game-2](https://user-images.githubusercontent.com/110962321/220714327-9ba3dc59-75dc-41bf-8584-fe673e9dcb2e.jpg)
![Mini_game-3](https://user-images.githubusercontent.com/110962321/220714335-63b85d80-01f0-4255-a581-a2413c78999f.jpg)
![Mini_game-4](https://user-images.githubusercontent.com/110962321/220714351-d4c12789-d730-42e2-a172-f7b19dd17995.jpg)
![Mini_game-5](https://user-images.githubusercontent.com/110962321/220714370-8c6dafa1-01a6-4ac3-83f0-a543dcff7c6b.jpg)

**Comment by Unlxii** [comment]
-------last concept -----
[YOUR WAY.pptx](https://github.com/Unlxii/projectcompro/files/10972029/YOUR.WAY.pptx)
